In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score



In [25]:
milk_fat_quality_dataset = pd.read_csv('milk_fat_predict2.csv')

In [26]:
milk_fat_quality_dataset.head()

Suhu  Rasa  Bau  Lemak  Kekeruhan  Warna  Grade
0    35     1    0      1          0    254      1
1    36     0    1      0          1    253      1
2    70     1    1      1          1    246      0
3    34     1    1      0          1    255      0
4    37     0    0      0          0    255      1

In [27]:
milk_fat_quality_dataset.shape

(1059, 7)

In [28]:
milk_fat_quality_dataset['Grade'].value_counts()

1    630
0    429
Name: Grade, dtype: int64

In [29]:
X = milk_fat_quality_dataset.drop (columns='Grade', axis=1)
Y = milk_fat_quality_dataset['Grade']

In [30]:
print(X)
print(Y)

      Suhu  Rasa  Bau  Lemak  Kekeruhan  Warna
0       35     1    0      1          0    254
1       36     0    1      0          1    253
2       70     1    1      1          1    246
3       34     1    1      0          1    255
4       37     0    0      0          0    255
...    ...   ...  ...    ...        ...    ...
1054    45     1    1      0          0    247
1055    38     1    0      1          0    255
1056    40     1    1      1          1    255
1057    43     1    0      1          0    250
1058    55     0    1      1          1    255

[1059 rows x 6 columns]
0       1
1       1
2       0
3       0
4       1
       ..
1054    1
1055    1
1056    0
1057    1
1058    0
Name: Grade, Length: 1059, dtype: int64


In [31]:
scaler = StandardScaler()

In [32]:
scaler.fit(X)

StandardScaler()

In [33]:
standarized_data = scaler.transform(X)

In [34]:
print(standarized_data)

[[-0.91410734  0.91050291 -0.87296233  0.69960809 -0.98221664  0.5016002 ]
 [-0.81503461 -1.09829413  1.1455248  -1.4293717   1.01810533  0.26933321]
 [ 2.55343832  0.91050291  1.1455248   0.69960809  1.01810533 -1.35653574]
 ...
 [-0.41874368  0.91050291  1.1455248   0.69960809  1.01810533  0.73386719]
 [-0.12152548  0.91050291 -0.87296233  0.69960809 -0.98221664 -0.42746777]
 [ 1.06734732 -1.09829413  1.1455248   0.69960809  1.01810533  0.73386719]]


In [35]:
X = standarized_data
Y = milk_fat_quality_dataset['Grade']

In [36]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.2, stratify=Y, random_state=2)

In [37]:
print(X.shape, X_train.shape, X_test.shape)

(1059, 6) (847, 6) (212, 6)


In [38]:
classifier = svm.SVC(kernel='linear')

In [39]:
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

In [40]:
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [41]:
print('Akurasi data training adalah =', training_data_accuracy)

Akurasi data training adalah = 0.8323494687131051


In [42]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [43]:
input_data = (35,1,0,1,0,254)
input_data_as_numpy_array = np.array(input_data)
input_data_reshape = input_data_as_numpy_array.reshape(1, -1)

std_data = scaler.transform(input_data_reshape)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction [0]== 0):
    print('Susu berkualitas tinggi lemak')
elif (prediction [0]== 1):
    print('Susu berkualitas tinggi lemak')


[[-0.91410734  0.91050291 -0.87296233  0.69960809 -0.98221664  0.5016002 ]]
[1]
Susu berkualitas tinggi lemak


c:\Users\YoungGix\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [44]:
import pickle

In [46]:
filename = 'milk_model.sav'
pickle.dump(classifier, open(filename,'wb'))